package javagroupproject;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author lingyanjiang
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        dashButton = new javax.swing.JButton();
        statReportButton = new javax.swing.JButton();
        otherReportButton = new javax.swing.JButton();
        customizeButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        graphPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        bgPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        bgPanel.setSize(new java.awt.Dimension(1000, 700));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setLayout(new javax.swing.OverlayLayout(topPanel));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/top.jpg"))); // NOI18N
        topPanel.add(jLabel1);

        bgPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        leftPanel.setBackground(new java.awt.Color(38, 42, 51));
        leftPanel.setPreferredSize(new java.awt.Dimension(177, 800));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_1.png")));
        dashButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_1p.png")));
        dashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashButtonActionPerformed(evt);
            }
        });
        leftPanel.add(dashButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 60));

        statReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_2.png")));
        statReportButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_2p.png")));
        leftPanel.add(statReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 60));

        otherReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_3.png")));
        otherReportButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_3p.png")));
        leftPanel.add(otherReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 60));

        customizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_4.png")));
        customizeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_4p.png")));
        leftPanel.add(customizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 60));

        bgPanel.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        graphPanel1.setLayout(new java.awt.BorderLayout());
        mainPanel.add(graphPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 210));

        bgPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 820, 620));

        getContentPane().add(bgPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashButtonActionPerformed
        ChartPanel p = null;
        try {
            p = JFreeChartTest.generateChart();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        addChart(p);
    }//GEN-LAST:event_dashButtonActionPerformed

    /**
     * This method add chart to the main panel
     * @param chart 
     */
    public void addChart(ChartPanel chart) {
        graphPanel1.add(chart,BorderLayout.CENTER);
        graphPanel1.validate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton customizeButton;
    private javax.swing.JButton dashButton;
    private javax.swing.JPanel graphPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton otherReportButton;
    private javax.swing.JButton statReportButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
